name: test code
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.16"
      - name: Install
        run: npm ci
      - name: Run format test
        run: npm run test:format
